pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "output"


validation_data:
  prompt: "gorgeous young women fighting in a brawl, in the style of Martine Johanna, draped in flowing fabric, ((((colorful)))) (((bright))) energetic brush strokes, realistic, sharp focus, 8k high definition, insanely detailed, intricate, elegant, art by Martine Johanna and artgerm, symmetrical"
  negative_prompt: "lowres, bad anatomy, bad hands, text, error, missing fingers, bad fingers, extra fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, bad face, bad eyes"
  video_length: 511
  width: 480
  height: 240
  num_inference_steps: 28
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50
  dataset_set: "val"


train_batch_size: 1
validation_steps: 100

resume_from_checkpoint: ./checkpoints/followyourpose_checkpoint-1000


seed: 33
mixed_precision: 'no'
gradient_checkpointing: False
enable_xformers_memory_efficient_attention: True
